server.port=8081
strix.window.seconds=30
strix.detection.watch-threshold=0.55
strix.detection.alert-threshold=0.60
strix.detection.min-events-for-alert=5

spring.datasource.url=jdbc:h2:file:./data/strix-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console